export const styles = {
    container: {
        padding: '16px',
        maxWidth: '600px',
        margin: '0 auto',
        paddingBottom: '32px',
    },
    heading: {
        fontSize: '22px',
        fontWeight: '700',
        color: '#1A1C1E',
        margin: '0 0 20px 0',
    },
    section: {
        backgroundColor: '#ffffff',
        borderRadius: '16px',
        overflow: 'hidden',
        marginBottom: '20px',
        boxShadow: '0 2px 8px rgba(0,0,0,0.06)',
        border: '1px solid #F2F2F7',
    },
    sectionHeader: {
        display: 'flex',
        justifyContent: 'space-between',
        alignItems: 'center',
        padding: '14px 16px',
        backgroundColor: '#1A1C1E',
    },
    sectionTitle: {
        fontSize: '16px',
        fontWeight: '700',
        color: '#ffffff',
    },
    roleBadge: {
        fontSize: '11px',
        backgroundColor: '#0064BC',
        color: '#ffffff',
        padding: '3px 10px',
        borderRadius: '20px',
        fontWeight: '600',
    },
    subSection: {
        padding: '16px',
        borderBottom: '1px solid #F2F2F7',
    },
    subSectionHeader: {
        display: 'flex',
        justifyContent: 'space-between',
        alignItems: 'center',
        marginBottom: '12px',
    },
    subHeading: {
        fontSize: '15px',
        fontWeight: '700',
        color: '#1A1C1E',
        margin: '0 0 12px 0',
    },
    form: {
        display: 'flex',
        flexDirection: 'column',
        gap: '10px',
    },
    formBox: {
        backgroundColor: '#F2F2F7',
        borderRadius: '12px',
        padding: '16px',
        marginBottom: '16px',
        border: '1px solid #E3E3E4',
    },
    formTitle: {
        fontSize: '14px',
        fontWeight: '700',
        color: '#1A1C1E',
        margin: '0 0 12px 0',
    },
    input: {
        padding: '10px 14px',
        borderRadius: '8px',
        border: '1.5px solid #E3E3E4',
        fontSize: '14px',
        outline: 'none',
        width: '100%',
        boxSizing: 'border-box',
        backgroundColor: '#ffffff',
    },
    textarea: {
        padding: '10px 14px',
        borderRadius: '8px',
        border: '1.5px solid #E3E3E4',
        fontSize: '14px',
        outline: 'none',
        width: '100%',
        boxSizing: 'border-box',
        resize: 'vertical',
        fontFamily: 'inherit',
    },
    button: {
        padding: '12px',
        borderRadius: '8px',
        backgroundColor: '#388e3c',
        color: '#ffffff',
        fontSize: '14px',
        fontWeight: '600',
        border: 'none',
        cursor: 'pointer',
        flex: 1,
    },
    secondaryButton: {
        padding: '12px',
        borderRadius: '8px',
        backgroundColor: 'transparent',
        color: '#555555',
        fontSize: '14px',
        border: '1.5px solid #E3E3E4',
        cursor: 'pointer',
        flex: 1,
    },
    smallButton: {
        padding: '6px 12px',
        borderRadius: '8px',
        backgroundColor: '#388e3c',
        color: '#ffffff',
        fontSize: '13px',
        fontWeight: '600',
        border: 'none',
        cursor: 'pointer',
    },
    iconButton: {
        background: 'none',
        border: 'none',
        fontSize: '18px',
        cursor: 'pointer',
        padding: '4px',
    },
    row: {
        display: 'flex',
        gap: '10px',
    },
    uploadRow: {
        display: 'flex',
        justifyContent: 'space-between',
        alignItems: 'center',
        marginTop: '16px',
    },
    uploadLabel: {
        fontSize: '14px',
        color: '#1A1C1E',
        fontWeight: '600',
    },
    uploadButton: {
        padding: '8px 16px',
        borderRadius: '8px',
        backgroundColor: '#E8F5E9',
        color: '#388e3c',
        fontSize: '13px',
        fontWeight: '600',
        cursor: 'pointer',
        border: '1.5px solid #B7DFB9',
    },
    currentLogo: {
        width: '64px',
        height: '64px',
        borderRadius: '12px',
        objectFit: 'cover',
        marginTop: '12px',
    },
    eventsList: {
        display: 'flex',
        flexDirection: 'column',
        gap: '8px',
    },
    manageEventCard: {
        display: 'flex',
        justifyContent: 'space-between',
        alignItems: 'center',
        padding: '10px 12px',
        backgroundColor: '#F2F2F7',
        borderRadius: '10px',
        border: '1px solid #F2F2F7',
    },
    manageEventInfo: {
        flex: 1,
        minWidth: 0,
    },
    manageEventTitle: {
        fontSize: '14px',
        fontWeight: '600',
        color: '#1A1C1E',
        margin: '0 0 2px 0',
    },
    manageEventDate: {
        fontSize: '12px',
        color: '#555555',
        margin: '0',
    },
    manageEventActions: {
        display: 'flex',
        gap: '4px',
        alignItems: 'center',
    },
    hint: {
        fontSize: '13px',
        color: '#AAAAAA',
        margin: '8px 0 0 0',
    },
    error: {
        fontSize: '13px',
        color: '#DC2626',
        backgroundColor: '#FEF2F2',
        padding: '8px 12px',
        borderRadius: '8px',
        margin: '4px 0',
    },
    success: {
        fontSize: '13px',
        color: '#16A34A',
        backgroundColor: '#F0FDF4',
        padding: '8px 12px',
        borderRadius: '8px',
        margin: '4px 0',
    },
    empty: {
        fontSize: '14px',
        color: '#555555',
        textAlign: 'center',
        padding: '40px 0',
    },
    devOrgItem: {
        backgroundColor: '#F2F2F7',
        borderRadius: '10px',
        border: '1px solid #F2F2F7',
        overflow: 'hidden',
        marginBottom: '8px',
    },
    devOrgHeader: {
        display: 'flex',
        alignItems: 'center',
        gap: '10px',
        padding: '10px 12px',
        cursor: 'pointer',
    },
    devOrgLogo: {
        width: '32px',
        height: '32px',
        borderRadius: '6px',
        objectFit: 'cover',
    },
    devOrgName: {
        flex: 1,
        fontSize: '14px',
        fontWeight: '600',
        color: '#1A1C1E',
    },
    devOrgExpanded: {
        padding: '12px',
        borderTop: '1px solid #E3E3E4',
    },
    arrow: {
        fontSize: '24px',
        color: '#AAAAAA',
        flexShrink: 0,
    },
    tabRow: {
        display: 'flex',
        gap: '8px',
        marginBottom: '12px',
    },
    tab: {
        flex: 1,
        padding: '8px',
        borderRadius: '8px',
        border: '1.5px solid #E3E3E4',
        backgroundColor: 'transparent',
        color: '#555555',
        fontSize: '13px',
        fontWeight: '600',
        cursor: 'pointer',
    },
    tabActive: {
        flex: 1,
        padding: '8px',
        borderRadius: '8px',
        border: '1.5px solid #388e3c',
        backgroundColor: '#E8F5E9',
        color: '#388e3c',
        fontSize: '13px',
        fontWeight: '600',
        cursor: 'pointer',
    },
    adminsList: {
        display: 'flex',
        flexDirection: 'column',
        gap: '8px',
        marginBottom: '16px',
    },
    adminCard: {
        display: 'flex',
        alignItems: 'center',
        justifyContent: 'space-between',
        padding: '10px 12px',
        backgroundColor: '#F2F2F7',
        borderRadius: '10px',
        border: '1px solid #F2F2F7',
    },
    adminInfo: {
        flex: 1,
        minWidth: 0,
    },
    adminName: {
        fontSize: '14px',
        fontWeight: '600',
        color: '#1A1C1E',
        margin: '0 0 2px 0',
    },
    adminEmail: {
        fontSize: '12px',
        color: '#555555',
        margin: '0 0 4px 0',
    },
    adminRoleBadge: {
        fontSize: '11px',
        backgroundColor: '#E5EFF9',
        color: '#0064BC',
        padding: '2px 8px',
        borderRadius: '20px',
        fontWeight: '600',
    },
    removeButton: {
        padding: '6px 12px',
        borderRadius: '8px',
        backgroundColor: '#FEF2F2',
        color: '#DC2626',
        fontSize: '12px',
        fontWeight: '600',
        border: '1px solid #FECACA',
        cursor: 'pointer',
        flexShrink: 0,
        marginLeft: '8px',
    },
    toggleButton: {
        padding: '8px 14px',
        borderRadius: '8px',
        backgroundColor: '#F2F2F7',
        color: '#1A1C1E',
        fontSize: '13px',
        fontWeight: '600',
        border: '1px solid #E3E3E4',
        cursor: 'pointer',
        marginBottom: '12px',
        width: '100%',
        textAlign: 'left',
    },
    deleteOrgButton: {
        background: 'none',
        border: 'none',
        fontSize: '16px',
        cursor: 'pointer',
        padding: '4px',
        flexShrink: 0,
    },
    fieldLabel: {
        fontSize: '12px',
        fontWeight: '600',
        color: '#555555',
        marginBottom: '-4px',
    },
}