"""replace location with coordinates

Revision ID: 06b38e1959f3
Revises: 6d078dd1ac7e
Create Date: 2026-05-15 16:53:52.320562

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '06b38e1959f3'
down_revision: Union[str, Sequence[str], None] = '6d078dd1ac7e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('organizations', sa.Column('location_name', sa.String(), nullable=True))
    op.add_column('organizations', sa.Column('latitude', sa.Float(), nullable=True))
    op.add_column('organizations', sa.Column('longitude', sa.Float(), nullable=True))
    op.drop_column('organizations', 'location')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('organizations', sa.Column('location', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_column('organizations', 'longitude')
    op.drop_column('organizations', 'latitude')
    op.drop_column('organizations', 'location_name')
    # ### end Alembic commands ###
