"""add short description to organizations

Revision ID: 65561fc5756b
Revises: 32dcaf116bc8
Create Date: 2026-05-17 16:05:26.862714

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '65561fc5756b'
down_revision: Union[str, Sequence[str], None] = '32dcaf116bc8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('organizations', sa.Column('short_description', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('organizations', 'short_description')
    # ### end Alembic commands ###
