"""add start notification sent flag

Revision ID: f8676f10dded
Revises: 61226d575e5f
Create Date: 2026-06-13 19:34:52.230048

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f8676f10dded'
down_revision: Union[str, Sequence[str], None] = '61226d575e5f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('events', sa.Column('start_notification_sent', sa.Boolean(), nullable=False, server_default='false'))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('events', 'start_notification_sent')
    # ### end Alembic commands ###
